(function(){
function escAI(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function addAIBox(){
  if(document.getElementById('aiBox')||!document.getElementById('cvTab'))return;
  const box=document.createElement('div');box.id='aiBox';box.className='section';box.innerHTML=`<div style="border:1px solid #dbe4ee;border-radius:13px;padding:16px;background:#f8fafc"><h2 style="margin:0 0 7px">🤖 Optimiza tu CV con IA</h2><p style="font-size:13px;color:#667085;margin:0 0 12px">Pega una oferta de empleo y CVGO adaptará tu perfil, experiencia, habilidades y palabras clave para ATS.</p><div class="field"><label>Oferta de empleo</label><textarea id="aiJob" placeholder="Pega aquí la oferta completa de empleo..."></textarea></div><button class="primary" id="aiBtn" onclick="generateAICV()">✨ Analizar oferta y optimizar mi CV</button><div id="aiMsg" style="font-size:13px;margin-top:10px"></div><div id="aiResult" style="margin-top:12px"></div></div>`;
  const cvTab=document.getElementById('cvTab');cvTab.insertBefore(box,cvTab.firstChild);
}
window.generateAICV=async function(){
  const btn=document.getElementById('aiBtn'),msg=document.getElementById('aiMsg'),out=document.getElementById('aiResult'),job=(document.getElementById('aiJob')?.value||'').trim();
  if(job.length<30){msg.textContent='Pega una oferta de empleo de al menos 30 caracteres.';msg.style.color='#b42318';return}
  const experience=[...document.querySelectorAll('#experience .item')].map(x=>({position:x.querySelector('.ep')?.value||'',company:x.querySelector('.ec')?.value||'',dates:(x.querySelector('.ef')?.value||'')+' - '+(x.querySelector('.et')?.value||''),description:x.querySelector('.ed')?.value||''}));
  const education=[...document.querySelectorAll('#education .item')].map(x=>({title:x.querySelector('.etitle')?.value||'',school:x.querySelector('.eschool')?.value||'',year:x.querySelector('.eyear')?.value||''}));
  const data={job_offer:job,name:window.val?val('name'):document.getElementById('name')?.value||'',role:document.getElementById('role')?.value||'',summary:document.getElementById('summary')?.value||'',skills:document.getElementById('skills')?.value||'',experience,education};
  btn.disabled=true;btn.textContent='⏳ Analizando oferta y generando CV...';msg.textContent='La IA está trabajando...';msg.style.color='#667085';out.innerHTML='';
  try{const r=await fetch('/api/ai-generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw j;const a=j.result||{};window._cvgoAI=a;
    out.innerHTML=`<div style="background:#fff;border:1px solid #eaecf0;border-radius:10px;padding:13px"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><b>Resultado de la optimización</b><strong>${Number(a.ats_score||0)}/100 ATS</strong></div><p style="font-size:13px"><b>${escAI(a.professional_title)}</b></p><p style="font-size:13px;line-height:1.5">${escAI(a.professional_summary)}</p><div style="font-size:12px"><b>Palabras clave:</b> ${escAI((a.ats_keywords||[]).join(', '))}</div><button class="primary" style="margin-top:12px" onclick="applyAICV()">✓ Aplicar al CV</button></div>`;msg.textContent='CV optimizado correctamente.';msg.style.color='#067647';
  }catch(e){msg.textContent=e.error==='AI_NOT_CONFIGURED'?'La IA aún no está configurada en el servidor.':e.error==='TRIAL_EXPIRED'?'Tu prueba gratuita ha terminado. Activa PRO para continuar.':e.error==='JOB_OFFER_REQUIRED'?'La oferta es demasiado corta.':'No se pudo generar el CV. Inténtalo de nuevo.';msg.style.color='#b42318'}finally{btn.disabled=false;btn.textContent='✨ Analizar oferta y optimizar mi CV'}
};
window.applyAICV=function(){const a=window._cvgoAI;if(!a)return;if(document.getElementById('role'))document.getElementById('role').value=a.professional_title||document.getElementById('role').value;if(document.getElementById('summary'))document.getElementById('summary').value=a.professional_summary||document.getElementById('summary').value;if(document.getElementById('skills'))document.getElementById('skills').value=(a.skills||[]).join(', ');const items=[...document.querySelectorAll('#experience .item')];(a.experiences||[]).forEach((e,i)=>{let x=items[i];if(!x&&typeof addExp==='function'){addExp();x=[...document.querySelectorAll('#experience .item')].at(-1)}if(x){x.querySelector('.ep').value=e.position||'';x.querySelector('.ec').value=e.company||'';let dates=(e.dates||'').split(' - ');x.querySelector('.ef').value=dates[0]||'';x.querySelector('.et').value=dates.slice(1).join(' - ')||'';x.querySelector('.ed').value=e.description||''}});if(typeof render==='function')render();document.getElementById('aiMsg').textContent='✓ Optimización aplicada a tu CV.';document.getElementById('aiMsg').style.color='#067647';window.scrollTo({top:0,behavior:'smooth'})};
const start=setInterval(()=>{if(document.getElementById('cvTab')){addAIBox();clearInterval(start)}},300);
})();