(function(){
'use strict';
function q(id){return document.getElementById(id)}
function styles(){
 if(q('cvgoImportUiStyles'))return;
 var s=document.createElement('style');s.id='cvgoImportUiStyles';s.textContent='#cvgoImport{display:none!important}.cvgoImportCard{margin:0 0 18px;padding:16px 18px;border:1px solid #cfe0f5;border-radius:14px;background:linear-gradient(135deg,#f7fbff,#fff);display:flex;align-items:center;justify-content:space-between;gap:18px}.cvgoImportCard b{display:block;font-size:15px;color:#172b4d;margin-bottom:4px}.cvgoImportCard p{margin:0;color:#667085;font-size:12px;line-height:1.4}.cvgoImportCard button{border:0;background:#2563eb;color:#fff;border-radius:9px;padding:10px 16px;font-weight:800;cursor:pointer;white-space:nowrap}.cvgoImportCard button:hover{background:#1d4ed8}.cvgoImportMsg{margin-top:8px;font-size:12px}.cvgoImportMsg.err{color:#b42318}.cvgoImportMsg.ok{color:#067647}.cvgoImportModal{position:fixed;inset:0;background:rgba(15,23,42,.5);display:flex;align-items:center;justify-content:center;padding:20px;z-index:100000}.cvgoImportModal>div{background:#fff;border-radius:18px;padding:24px;max-width:460px;width:100%;box-shadow:0 25px 70px rgba(0,0,0,.25)}.cvgoImportModal h3{margin:0 0 8px}.cvgoImportActions{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}.cvgoImportActions button{border:0;border-radius:9px;padding:10px 15px;font-weight:800;cursor:pointer}.cvgoImportActions .cancel{background:#eef2f6;color:#344054}.cvgoImportActions .apply{background:#111827;color:#fff}@media(max-width:600px){.cvgoImportCard{align-items:flex-start;flex-direction:column}.cvgoImportCard button{width:100%}}';document.head.appendChild(s)
}
function setVal(id,v){var e=q(id);if(!e||v==null)return;e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}))}
function fillExp(items){var box=q('experience');if(!box)return;box.innerHTML='';if(!items.length){if(typeof addExp==='function')addExp();return}items.forEach(function(x){if(typeof addExp!=='function')return;addExp();var all=box.querySelectorAll('.item'),it=all[all.length-1];if(!it)return;[['.ep',x.position],['.ec',x.company],['.ef',x.from],['.et',x.to],['.ed',x.description]].forEach(function(a){var e=it.querySelector(a[0]);if(e){e.value=a[1]||'';e.dispatchEvent(new Event('input',{bubbles:true}))}})})}
function fillEdu(items){var box=q('education');if(!box)return;box.innerHTML='';if(!items.length){if(typeof addEdu==='function')addEdu();return}items.forEach(function(x){if(typeof addEdu!=='function')return;addEdu();var all=box.querySelectorAll('.item'),it=all[all.length-1];if(!it)return;[['.etitle',x.title],['.eschool',x.school],['.eyear',x.year]].forEach(function(a){var e=it.querySelector(a[0]);if(e){e.value=a[1]||'';e.dispatchEvent(new Event('input',{bubbles:true}))}})})}
function apply(data){['name','role','email','phone','city','linkedin','summary','skills'].forEach(function(k){setVal(k,data[k])});fillExp(data.experience||[]);fillEdu(data.education||[]);if(typeof render==='function')render()}
function confirmImport(data,pages,msg){var old=q('cvgoImportModal');if(old)old.remove();var o=document.createElement('div');o.id='cvgoImportModal';o.className='cvgoImportModal';o.innerHTML='<div><h3>⚠️ Reemplazar el contenido actual</h3><p>La información encontrada en tu PDF sustituirá los datos que tienes actualmente en el CV. ¿Quieres continuar?</p><div class="cvgoImportActions"><button class="cancel">Cancelar</button><button class="apply">Sí, importar CV</button></div></div>';document.body.appendChild(o);o.querySelector('.cancel').onclick=function(){o.remove()};o.querySelector('.apply').onclick=function(){o.remove();apply(data);msg.className='cvgoImportMsg ok';msg.textContent='✓ CV importado correctamente. Revisa los datos antes de descargarlo.'};o.onclick=function(e){if(e.target===o)o.remove()}}
function addUI(){
 var tab=q('cvTab');if(!tab)return false;
 if(q('cvgoImportCard'))return true;
 styles();var card=document.createElement('div');card.id='cvgoImportCard';card.className='cvgoImportCard';card.innerHTML='<div><b>📄 Importa tu CV automáticamente</b><p>Sube tu CV en PDF y CVProfit extraerá tus datos para rellenar el formulario.</p><div id="cvgoImportMsg" class="cvgoImportMsg"></div></div><button type="button" id="cvgoImportLaunch">Importar mi CV</button><input id="cvgoImportFile" type="file" accept="application/pdf,.pdf" hidden>';
 var tabs=tab.parentElement.querySelector('.tabs');if(tabs&&tabs.nextElementSibling===tab)tabs.insertAdjacentElement('afterend',card);else tab.insertBefore(card,tab.firstChild);
 var btn=q('cvgoImportLaunch'),file=q('cvgoImportFile'),msg=q('cvgoImportMsg');
 btn.onclick=function(){file.click()};file.onchange=async function(){var f=file.files&&file.files[0];if(!f)return;btn.disabled=true;msg.className='cvgoImportMsg';msg.textContent='⏳ Analizando tu CV...';var fd=new FormData();fd.append('file',f);try{var r=await fetch('/api/cv-import',{method:'POST',body:fd,credentials:'same-origin'}),j=await r.json();if(!r.ok)throw j;confirmImport(j.data,j.pages,msg)}catch(e){var t=e&&e.error==='PDF_ONLY'?'Solo puedes subir un archivo PDF.':e&&e.error==='FILE_TOO_LARGE'?'El PDF pesa demasiado (máximo 8 MB).':e&&e.error==='PDF_NO_TEXT'?'No hemos podido leer texto del PDF.':e&&e.error==='TRIAL_EXPIRED'?'Tu prueba gratuita ha terminado. Activa PRO para importar tu CV.':e&&e.error==='AI_NOT_CONFIGURED'?'La importación inteligente no está configurada todavía.':'No hemos podido importar el CV. Comprueba el PDF e inténtalo de nuevo.';msg.className='cvgoImportMsg err';msg.textContent='⚠ '+t}finally{btn.disabled=false;file.value=''}};
 return true
}
function init(){styles();addUI()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
var tries=0,t=setInterval(function(){if(addUI()||++tries>80)clearInterval(t)},250);
new MutationObserver(function(){addUI()}).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
})();
