from flask import Response


def register_legal(app):
    def page(title, body):
        return Response(f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — CVProfit</title><style>body{{margin:0;background:#f4f6fa;color:#101828;font-family:Inter,Arial,sans-serif;line-height:1.65}}header{{height:72px;background:#111827;color:#fff;display:flex;align-items:center;padding:0 6%;justify-content:space-between}}header a{{color:#fff;text-decoration:none;font-weight:900;font-size:26px}}main{{max-width:900px;margin:40px auto;padding:0 22px}}.card{{background:#fff;border:1px solid #e4e7ec;border-radius:18px;padding:32px;box-shadow:0 8px 30px #1018280c}}h1{{margin-top:0;font-size:30px}}h2{{margin-top:28px;font-size:19px}}p,li{{font-size:14px;color:#344054}}.notice{{background:#fffaeb;border:1px solid #fedf89;color:#7a2e0b;padding:14px 16px;border-radius:10px;font-size:13px}}a{{color:#175cd3}}footer{{text-align:center;padding:30px 20px;color:#667085;font-size:12px}}footer a{{margin:0 8px}}</style></head><body><header><a href="/">CVProfit</a><span>Información legal</span></header><main><div class="card">{body}</div></main><footer><a href="/legal/aviso-legal">Aviso legal</a><a href="/legal/privacidad">Privacidad</a><a href="/legal/cookies">Cookies</a><a href="/legal/condiciones">Condiciones</a><a href="/legal/reembolsos">Cancelación y reembolsos</a><br><br>© 2026 CVProfit</footer></body></html>''', mimetype='text/html')

    @app.get('/legal/aviso-legal')
    def legal_notice():
        return page('Aviso legal', '''<h1>Aviso legal</h1><div class="notice"><strong>Información pendiente de completar antes del lanzamiento comercial:</strong> los datos identificativos del titular y prestador del servicio deben incorporarse en esta página. CVProfit no presenta esta versión como aviso legal definitivo.</div><h2>1. Identificación del titular</h2><p><strong>Nombre o denominación:</strong> [PENDIENTE]</p><p><strong>NIF/CIF:</strong> [PENDIENTE]</p><p><strong>Domicilio:</strong> [PENDIENTE]</p><p><strong>Correo electrónico de contacto:</strong> [PENDIENTE]</p><h2>2. Actividad</h2><p>CVProfit ofrece herramientas digitales para la creación, edición y optimización de currículums, cartas de presentación y preparación de entrevistas mediante tecnología de inteligencia artificial.</p><h2>3. Propiedad intelectual</h2><p>Los elementos gráficos, código, diseño, textos, marca y demás contenidos propios de CVProfit están protegidos por la normativa aplicable. No se permite su reproducción o explotación sin autorización cuando resulte exigible.</p><h2>4. Responsabilidad</h2><p>CVProfit proporciona herramientas de asistencia. El usuario es responsable de revisar la información generada y de la exactitud de los datos que incorpore en su candidatura.</p><h2>5. Legislación aplicable</h2><p>La información y condiciones de uso se regirán por la normativa española y europea que resulte aplicable.</p>''')

    @app.get('/legal/privacidad')
    def privacy():
        return page('Política de privacidad', '''<h1>Política de privacidad</h1><div class="notice"><strong>Versión de trabajo:</strong> antes del lanzamiento comercial deberán completarse los datos del responsable del tratamiento y revisarse jurídicamente los proveedores y transferencias internacionales que correspondan.</div><h2>1. Responsable</h2><p><strong>Responsable del tratamiento:</strong> [PENDIENTE]</p><p><strong>Contacto:</strong> [PENDIENTE]</p><h2>2. Datos tratados</h2><p>CVProfit puede tratar datos de cuenta, como correo electrónico y credenciales protegidas, así como los datos que el usuario introduzca voluntariamente en su currículum, experiencia profesional, formación, habilidades y otra información de candidatura.</p><p>Para proteger el acceso a la prueba gratuita frente a abusos, CVProfit puede generar identificadores técnicos anonimizados mediante funciones hash a partir de señales como el identificador del navegador, la dirección IP y el correo utilizado para registrarse. No se almacenan las direcciones IP ni los identificadores del dispositivo en claro. Estas señales se utilizan exclusivamente para detectar reutilización abusiva de la prueba y se conservan dentro de una ventana limitada de 30 días.</p><h2>3. Finalidades</h2><ul><li>Crear y guardar la cuenta del usuario.</li><li>Permitir la creación, edición y descarga del CV.</li><li>Prestar las funciones PRO contratadas.</li><li>Analizar ofertas de empleo y generar sugerencias mediante IA cuando el usuario utilice dichas funciones.</li><li>Gestionar pagos, suscripciones y cancelaciones.</li><li>Prevenir el uso abusivo o automatizado de las pruebas gratuitas.</li><li>Cumplir obligaciones legales y atender solicitudes de soporte.</li></ul><h2>4. Proveedores</h2><p>El servicio puede utilizar proveedores tecnológicos para alojamiento, base de datos, pagos y funciones de inteligencia artificial. La versión definitiva de esta política deberá identificar los proveedores concretos y las garantías aplicables.</p><h2>5. Conservación</h2><p>Los datos se conservarán durante el tiempo necesario para prestar el servicio y, posteriormente, durante los plazos necesarios para cumplir obligaciones legales o atender responsabilidades. Los registros técnicos utilizados exclusivamente para prevenir abusos de la prueba se eliminan después de la ventana de 30 días.</p><h2>6. Derechos</h2><p>Las personas usuarias podrán ejercer los derechos que les reconozca la normativa aplicable, incluyendo acceso, rectificación, supresión, oposición, limitación y portabilidad cuando proceda, mediante el canal de contacto que se indique en la versión definitiva.</p><h2>7. Seguridad</h2><p>CVProfit aplica medidas técnicas y organizativas destinadas a proteger la información frente a accesos no autorizados, pérdida o alteración.</p>''')

    @app.get('/legal/cookies')
    def cookies():
        return page('Política de cookies', '''<h1>Política de cookies</h1><h2>1. Qué utiliza CVProfit</h2><p>CVProfit utiliza cookies o mecanismos equivalentes estrictamente necesarios para mantener la sesión del usuario y permitir el funcionamiento de la cuenta y del servicio.</p><h2>2. Protección de la prueba gratuita</h2><p>Durante el registro de una prueba gratuita, CVProfit puede utilizar una cookie técnica de seguridad, sin publicidad ni analítica, para ayudar a evitar la creación repetida de cuentas con el mismo navegador durante la ventana antifraude. Esta cookie se configura con atributos de seguridad y tiene una duración máxima de 30 días.</p><h2>3. Cookies no necesarias</h2><p>En esta versión no se activa ninguna cookie analítica o publicitaria de terceros por defecto. Si en el futuro se incorporan tecnologías no exentas, se añadirá el correspondiente mecanismo de consentimiento y configuración.</p><h2>4. Cookies técnicas</h2><p>Las cookies estrictamente necesarias para prestar el servicio solicitado por el usuario pueden quedar exceptuadas del consentimiento previo cuando cumplan los requisitos establecidos por la normativa aplicable.</p><h2>5. Gestión</h2><p>Las personas usuarias pueden gestionar o eliminar cookies desde la configuración de su navegador. La eliminación de esta cookie de seguridad no implica que se eliminen los registros antifraude asociados en el servidor.</p>''')

    @app.get('/legal/condiciones')
    def terms():
        return page('Condiciones de uso y contratación', '''<h1>Condiciones de uso y contratación</h1><div class="notice"><strong>Versión de trabajo:</strong> los datos identificativos del titular y cualquier condición específica de contratación deberán completarse antes de la venta pública.</div><h2>1. Servicio</h2><p>CVProfit ofrece herramientas digitales para crear CV, adaptar candidaturas, analizar compatibilidad ATS, generar cartas y practicar entrevistas.</p><h2>2. Cuenta</h2><p>El usuario debe proporcionar información veraz y mantener la confidencialidad de sus credenciales.</p><h2>3. Prueba gratuita</h2><p>Las nuevas cuentas disponen de un periodo gratuito de 3 días con acceso a las funciones habilitadas durante la prueba. No se realiza un cobro durante esos 3 días. Finalizado el periodo, el usuario debe contratar PRO si desea continuar utilizando las funciones restringidas. La prueba está limitada para evitar el uso repetido o abusivo mediante la creación sucesiva de cuentas.</p><h2>4. PRO</h2><p>CVProfit PRO se ofrece mediante suscripción mensual de 9,99 € o anual de 59,99 €, impuestos incluidos cuando corresponda. La suscripción se renueva automáticamente según el plan contratado salvo cancelación.</p><h2>5. Cancelación</h2><p>El usuario puede cancelar la renovación de su suscripción desde la cuenta cuando esa función esté disponible. La cancelación de la renovación no elimina el acceso ya pagado hasta el final del periodo contratado.</p><h2>6. Inteligencia artificial</h2><p>Las funciones de IA son herramientas de asistencia y no garantizan la obtención de empleo, entrevistas o resultados concretos. El usuario debe revisar el contenido antes de utilizarlo.</p><h2>7. Aceptación</h2><p>El uso del servicio y la contratación de PRO quedan sujetos a estas condiciones y a la política de privacidad aplicable.</p>''')

    @app.get('/legal/reembolsos')
    def refunds():
        return page('Cancelación, desistimiento y reembolsos', '''<h1>Cancelación, desistimiento y reembolsos</h1><div class="notice"><strong>Importante:</strong> esta página contiene una estructura informativa y debe revisarse jurídicamente antes del lanzamiento comercial, especialmente en relación con el derecho de desistimiento y el inicio inmediato de servicios digitales.</div><h2>1. Cancelación de la renovación</h2><p>La cancelación evita futuras renovaciones. Cuando proceda, el acceso permanecerá activo hasta el final del periodo ya contratado.</p><h2>2. Derecho de desistimiento</h2><p>La normativa de consumidores contempla con carácter general un plazo de desistimiento de 14 días, pero existen excepciones para determinados servicios y contenidos digitales cuando se cumplen los requisitos legales y existe consentimiento previo e información adecuada.</p><h2>3. Solicitudes</h2><p>Las solicitudes de desistimiento, cancelación o reembolso se gestionarán a través del canal de contacto que se publique en la versión definitiva de esta página.</p><h2>4. Reembolsos</h2><p>Cuando legalmente corresponda un reembolso, se realizará conforme a la normativa aplicable y al medio de pago utilizado, salvo que legalmente proceda otra modalidad.</p>''')

    original_home = app.view_functions.get('home')
    if original_home:
        def home_with_footer():
            response = original_home()
            html = response.get_data(as_text=True)
            footer = '''<footer id="cvgoLegalFooter" style="text-align:center;padding:28px 20px 35px;color:#667085;font-size:12px"><span style="display:block;margin-bottom:10px;font-weight:800;color:#344054">CVProfit</span><a href="/legal/aviso-legal" style="margin:0 7px;color:#667085">Aviso legal</a><a href="/legal/privacidad" style="margin:0 7px;color:#667085">Privacidad</a><a href="/legal/cookies" style="margin:0 7px;color:#667085">Cookies</a><a href="/legal/condiciones" style="margin:0 7px;color:#667085">Condiciones</a><a href="/legal/reembolsos" style="margin:0 7px;color:#667085">Cancelación y reembolsos</a></footer>'''
            html = html.replace('</body>', footer + '</body>')
            return Response(html, mimetype='text/html')
        app.view_functions['home'] = home_with_footer
