(function(){
  const $=id=>document.getElementById(id);
  const cats={
    profesional:[['p1','Profesional 01','Corporativo'],['p2','Profesional 02','Teal'],['p3','Profesional 03','Lateral'],['p4','Profesional 04','Verde']],
    moderno:[['m1','Moderno 01','Violeta'],['m2','Moderno 02','Coral'],['m3','Moderno 03','Turquesa'],['m4','Moderno 04','Ámbar']],
    minimalista:[['n1','Minimal 01','Negro'],['n2','Minimal 02','Petróleo'],['n3','Minimal 03','Verde'],['n4','Minimal 04','Burdeos']],
    creativo:[['c1','Creativo 01','Naranja'],['c2','Creativo 02','Púrpura'],['c3','Creativo 03','Turquesa'],['c4','Creativo 04','Rosa']],
    ejecutivo:[['e1','Ejecutivo 01','Carbón'],['e2','Ejecutivo 02','Dorado'],['e3','Ejecutivo 03','Borgoña'],['e4','Ejecutivo 04','Oliva']]
  };
  const legacy={classic:'p1',modern:'m1',minimal:'n1'};
  let selected=legacy[window.tpl]||window.tpl||'p1'; window.tpl=selected;
  const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  function data(){
    const v=id=>$(id)?.value?.trim()||'';
    const ex=[...document.querySelectorAll('#experience .item')].map(x=>({p:x.querySelector('.ep')?.value||'',c:x.querySelector('.ec')?.value||'',f:x.querySelector('.ef')?.value||'',t:x.querySelector('.et')?.value||'',d:x.querySelector('.ed')?.value||''})).filter(x=>x.p||x.c||x.d);
    const ed=[...document.querySelectorAll('#education .item')].map(x=>({t:x.querySelector('.etitle')?.value||'',s:x.querySelector('.eschool')?.value||'',y:x.querySelector('.eyear')?.value||''})).filter(x=>x.t||x.s);
    return {name:v('name')||'Tu nombre',role:v('role')||'Tu puesto profesional',email:v('email'),phone:v('phone'),city:v('city'),linkedin:v('linkedin'),summary:v('summary')||'Añade aquí un resumen profesional de 3–5 líneas.',skills:v('skills').split(',').map(x=>x.trim()).filter(Boolean),ex,ed,photo:window.cvgoPhotoData||''};
  }
  const contact=d=>[d.email,d.phone,d.city,d.linkedin].filter(Boolean).map(esc).join(' · ')||'Email · Teléfono · Ciudad';
  const photo=d=>d.photo?`<img class="tp" src="${d.photo}" alt="Foto profesional">`:'';
  const skills=d=>d.skills.length?`<div class="skills">${d.skills.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:'';
  const exp=d=>d.ex.map(x=>`<article class="job"><div class="jobhead"><b>${esc(x.p)}${x.c?' — '+esc(x.c):''}</b><span>${esc(x.f)}${x.f||x.t?' – ':''}${esc(x.t)}</span></div>${x.d?`<p>${esc(x.d).replace(/\n/g,'<br>')}</p>`:''}</article>`).join('');
  const edu=d=>d.ed.map(x=>`<article class="job"><div class="jobhead"><b>${esc(x.t)}</b><span>${esc(x.y)}</span></div>${x.s?`<p>${esc(x.s)}</p>`:''}</article>`).join('');
  function content(d){return `<section><h3>Perfil profesional</h3><p>${esc(d.summary)}</p></section>${d.ex.length?`<section><h3>Experiencia profesional</h3>${exp(d)}</section>`:''}${d.ed.length?`<section><h3>Formación</h3>${edu(d)}</section>`:''}${d.skills.length?`<section><h3>Habilidades</h3>${skills(d)}</section>`:''}`;}
  function render(id){
    const d=data(),p=photo(d),c=contact(d);
    const side=/^m1$|^m3$|^p3$/.test(id);
    const reverse=id==='m3';
    const html=`<div class="cv tm ${id} ${side?'hasSide':''} ${reverse?'reverse':''}">
      <header class="cvhead">${p}<div class="identity"><span class="eyebrow">${id[0]==='e'?'EXECUTIVE PROFILE':id[0]==='c'?'CURRÍCULUM':id[0]==='m'?'PERFIL PROFESIONAL':''}</span><h1>${esc(d.name)}</h1><div class="role">${esc(d.role)}</div></div><div class="headerContact">${c}</div></header>
      <aside class="sidePanel">${p}<h2>${esc(d.name)}</h2><div class="role">${esc(d.role)}</div><div class="sideContact">${c}</div>${skills(d)}</aside>
      <main>${content(d)}</main>
    </div>`;
    $('preview').innerHTML=html;
  }
  function styles(){
    if($('cvgoTemplateStyles'))return;
    const s=document.createElement('style');s.id='cvgoTemplateStyles';s.textContent=`
      .templateBtns{display:none!important}.cvgoTemplateNav{border:1px solid #eaecf0;border-radius:14px;padding:14px;background:#fff;margin-bottom:24px}.cvgoCats{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.cvgoCat{border:1px solid #d0d5dd;background:#fff;border-radius:9px;padding:8px 10px;font-size:12px;font-weight:800;cursor:pointer}.cvgoCat.active{background:#111827;color:#fff}.cvgoModels{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.cvgoModel{border:1px solid #d0d5dd;border-radius:10px;background:#fff;padding:8px;text-align:left;cursor:pointer}.cvgoModel.active{border:2px solid #111827;padding:7px}.thumb{height:76px;border-radius:6px;background:#f2f4f7;position:relative;overflow:hidden;margin-bottom:7px}.thumb:after{content:'';position:absolute;inset:8px 12px;background:#fff;box-shadow:0 2px 5px #0002}.thumb:before{content:'';position:absolute;z-index:2;background:#111827}.thumb[data-id^=p]:before{left:12px;right:12px;top:8px;height:10px}.thumb[data-id^=m]:before{left:8px;top:8px;bottom:8px;width:24%}.thumb[data-id^=n]:before{left:12px;right:12px;top:8px;height:4px}.thumb[data-id^=c]:before{left:8px;top:8px;bottom:8px;width:8px}.thumb[data-id^=e]:before{left:8px;right:8px;top:8px;height:18px}.cvgoModel b{font-size:11px;display:block}.cvgoModel small{font-size:10px;color:#667085}
      .tm{--accent:#17324d;--soft:#eef2f5;--ink:#172033;width:794px;min-height:1123px;height:auto;margin:0 auto;background:#fff;color:var(--ink);position:relative;box-shadow:0 3px 20px #0002;font-family:Arial,Helvetica,sans-serif;overflow:visible}.tm *{box-sizing:border-box;min-width:0}.tm h1{margin:0;font-size:34px;line-height:1.08;overflow-wrap:anywhere}.tm h2{margin:0;font-size:26px;line-height:1.1;overflow-wrap:anywhere}.tm .role{font-size:14px;color:#667085;margin-top:7px;line-height:1.3;overflow-wrap:anywhere}.tm .contact,.tm .headerContact,.tm .sideContact{font-size:10px;line-height:1.5;overflow-wrap:anywhere;word-break:break-word}.tm .tp{width:92px;height:92px;border-radius:50%;object-fit:cover;border:3px solid #fff;box-shadow:0 2px 10px #0002;flex:none}.tm .cvhead{padding:48px 58px;display:flex;align-items:center;gap:25px;border-bottom:2px solid var(--accent);position:relative}.tm .identity{min-width:0}.tm .eyebrow{display:block;font-size:9px;letter-spacing:2px;font-weight:800;color:var(--accent);margin-bottom:7px}.tm .headerContact{margin-left:auto;max-width:210px;text-align:right;color:#667085}.tm main{padding:38px 58px;min-width:0}.tm section{margin-bottom:22px}.tm section h3{font-size:12px;text-transform:uppercase;letter-spacing:1.5px;color:var(--accent);margin:0 0 9px;line-height:1.25}.tm section>p{font-size:11.5px;line-height:1.55;margin:0;overflow-wrap:anywhere;word-break:break-word}.tm .job{margin-bottom:13px;break-inside:avoid}.tm .jobhead{display:grid;grid-template-columns:minmax(0,1fr) minmax(70px,150px);gap:12px;align-items:start;font-size:11.5px;line-height:1.35}.tm .jobhead b{overflow-wrap:anywhere}.tm .jobhead span{text-align:right;color:#667085;overflow-wrap:anywhere;word-break:break-word}.tm .job p{font-size:10.5px;line-height:1.45;margin:4px 0 0;overflow-wrap:anywhere;word-break:break-word}.tm .skills{display:flex;flex-wrap:wrap;gap:5px}.tm .skills span{font-size:9.5px;background:var(--soft);border-radius:5px;padding:5px 7px;max-width:100%;overflow-wrap:anywhere}.sidePanel{display:none}
      .p1{--accent:#17324d;--soft:#edf3f7;padding-bottom:50px}.p1 .tp{order:2;margin-left:auto}.p1 .headerContact{display:block}.p2{--accent:#0f766e;--soft:#e7f5f2}.p2 .cvhead{border-bottom-width:3px}.p2 .tp{width:82px;height:82px;order:2;margin-left:auto}.p3{--accent:#49657a;--soft:#dfe7ec;display:grid;grid-template-columns:225px minmax(0,1fr);min-height:1123px}.p3 .cvhead{display:none}.p3 .sidePanel{display:block;background:var(--soft);padding:50px 25px}.p3 .sidePanel .tp{display:block;margin:0 auto 18px}.p3 .sidePanel .role{font-size:12px}.p3 .sideContact{margin:14px 0 22px}.p3 .sidePanel .skills{display:block}.p3 .sidePanel .skills span{display:block;margin-bottom:5px}.p3 main{padding:52px 42px}.p4{--accent:#285943;--soft:#eaf3ed}.p4 .tp{width:88px;height:88px;order:2;margin-left:auto}.p4 .eyebrow{color:#285943}
      .m1{--accent:#6d45b8;--soft:#eee8fb;display:grid;grid-template-columns:235px minmax(0,1fr);min-height:1123px}.m1 .cvhead,.m3 .cvhead{display:none}.m1 .sidePanel{display:block;background:#6d45b8;color:#fff;padding:48px 26px}.m1 .sidePanel .tp{display:block;margin:0 auto 18px;border-color:#e8ddff}.m1 .sidePanel h2{font-size:28px}.m1 .sidePanel .role,.m1 .sidePanel .sideContact{color:#f1eaff}.m1 .sidePanel .skills span{background:#825fc7;color:#fff}.m1 main{padding:50px 42px}.m1 section h3{color:#6d45b8}
      .m2{--accent:#d85c4a;--soft:#fff0ed}.m2 .cvhead{background:#d85c4a;color:#fff;border:0}.m2 .eyebrow,.m2 .role,.m2 .headerContact{color:#fff}.m2 .tp{border-color:#fff;order:2;margin-left:auto}.m2 main{padding:42px 58px}.m2 section h3{color:#d85c4a}
      .m3{--accent:#149a9a;--soft:#e6f7f7;display:grid;grid-template-columns:minmax(0,1fr) 205px;min-height:1123px}.m3 .cvhead{display:none}.m3 .sidePanel{display:block;order:2;background:#149a9a;color:#fff;padding:45px 23px}.m3 .sidePanel .tp{display:block;margin:0 auto 16px;border-color:#fff}.m3 .sidePanel h2{font-size:25px}.m3 .sidePanel .role,.m3 .sidePanel .sideContact{color:#e8ffff}.m3 .sidePanel .skills span{background:#3eafaf;color:#fff}.m3 main{padding:42px 48px}.m3 section h3{color:#149a9a}
      .m4{--accent:#c58a24;--soft:#fff6e4}.m4 .number{color:#c58a24}.m4 .cvhead{border-bottom-color:#c58a24}.m4 .tp{margin-left:auto}.m4 section h3{border-left:4px solid #c58a24;padding-left:9px;color:#8b651b}
      .n1{--accent:#171717;--soft:#f2f2f2}.n1 .cvhead{border-top:4px solid #171717}.n1 .tp{width:80px;height:80px;margin-left:auto}.n2{--accent:#245c68;--soft:#e9f1f3}.n2 .cvhead{text-align:center;display:block;border-bottom:1px solid #245c68}.n2 .tp{width:76px;height:76px;margin:0 auto 14px}.n2 .headerContact{max-width:none;text-align:center;margin-top:10px}.n3{--accent:#4f7d62;--soft:#edf4ef}.n3 .cvhead{border-bottom-color:#4f7d62}.n3 .tp{width:80px;height:80px;margin-left:auto}.n3 main{padding-top:35px}.n4{--accent:#8b2f3c;--soft:#f7edef}.n4 .cvhead{border-bottom-color:#8b2f3c}.n4 .tp{width:82px;height:82px;margin-left:auto}.n4 .initial{color:#8b2f3c}
      .c1{--accent:#e47732;--soft:#fff0e5}.c1 .cvhead{background:#e47732;color:#fff;border:0}.c1 .eyebrow,.c1 .role,.c1 .headerContact{color:#fff}.c1 .tp{order:2;margin-left:auto}.c1 main{padding:34px 55px}.c1 section:first-child{border-left:7px solid #e47732;background:#fff3e8;padding:15px 20px}.c2{--accent:#7b3fa1;--soft:#f3ebf8}.c2 .cvhead{border-left:16px solid #7b3fa1;padding-left:42px}.c2 .tp{order:2;margin-left:auto;border-color:#7b3fa1}.c2 main{padding-top:34px}.c3{--accent:#139b9b;--soft:#e8f7f7}.c3 .cvhead{border-bottom-color:#139b9b}.c3 .tp{width:90px;height:90px;border-color:#139b9b}.c3 main{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:13px}.c3 main section{border:1px solid #bfe3e3;border-radius:10px;padding:15px}.c4{--accent:#d94f8a;--soft:#fff0f6}.c4 .cvhead{display:block;text-align:center;border-bottom:3px solid #d94f8a}.c4 .tp{width:112px;height:112px;margin:0 auto 18px;border-color:#d94f8a}.c4 .headerContact{max-width:none;text-align:center;margin-top:12px}.c4 main{margin-top:28px}.c4 section h3{display:inline-block;border-bottom:2px solid #d94f8a;color:#d94f8a}
      .e1{--accent:#25272b;--soft:#eeeeef}.e1 .cvhead{background:#25272b;color:#fff;border:0}.e1 .eyebrow,.e1 .role,.e1 .headerContact{color:#d5d7da}.e1 .tp{order:2;margin-left:auto}.e1 main{padding:42px 58px}.e2{--accent:#b58b2a;--soft:#faf4e4;font-family:Georgia,serif}.e2 .cvhead{border-bottom-color:#b58b2a}.e2 .tp{width:84px;height:84px;border-color:#b58b2a;margin-left:auto}.e2 .role,.e2 .headerContact,.e2 .job,.e2 section>p{font-family:Arial,Helvetica,sans-serif}.e3{--accent:#7d2735;--soft:#f8ecef}.e3 .cvhead{border-bottom:5px solid #7d2735}.e3 .tp{width:96px;height:96px;border-color:#7d2735;margin-left:auto}.e4{--accent:#66734a;--soft:#f0f3eb}.e4 .cvhead{border-bottom-color:#66734a}.e4 .tp{width:84px;height:84px;margin-left:auto}.e4 .headerContact{max-width:180px}
      @media print{.tm{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important;box-shadow:none!important}.cvgoTemplateNav{display:none!important}.job{break-inside:avoid}.tm section h3{break-after:avoid}}
      @media(max-width:950px){.cvgoModels{grid-template-columns:1fr 1fr}.tm{width:100%;min-height:0}.p3,.m1,.m3{grid-template-columns:30% 70%}.c3 main{grid-template-columns:1fr}.cvgoCats{overflow:auto;flex-wrap:nowrap}}
    `;document.head.appendChild(s);
  }
  function buildNav(){
    const sec=[...document.querySelectorAll('#cvTab .section')].find(x=>x.querySelector('.templateBtns'));if(!sec||$('cvgoTemplateNav'))return;styles();
    const old=sec.querySelector('.templateBtns');if(old)old.style.display='none';
    const n=document.createElement('div');n.id='cvgoTemplateNav';n.className='cvgoTemplateNav';
    const list=[['profesional','Profesional'],['moderno','Moderno'],['minimalista','Minimalista'],['creativo','Creativo'],['ejecutivo','Ejecutivo']];
    n.innerHTML=`<b style="font-size:14px">🎨 Elige el diseño de tu CV</b><div class="cvgoCats">${list.map((x,i)=>`<button type="button" class="cvgoCat ${i?'':'active'}" data-cat="${x[0]}">${x[1]}</button>`).join('')}</div><div id="cvgoModels" class="cvgoModels"></div>`;
    sec.insertBefore(n,old||null);n.querySelectorAll('.cvgoCat').forEach(b=>b.onclick=()=>{n.querySelectorAll('.cvgoCat').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(b.dataset.cat)});draw('profesional');
  }
  function draw(cat){const b=$('cvgoModels');if(!b)return;b.innerHTML=cats[cat].map(x=>`<button type="button" class="cvgoModel ${selected===x[0]?'active':''}" data-id="${x[0]}"><div class="thumb" data-id="${x[0]}"></div><b>${x[1]}</b><small>${x[2]}${x[0]!=='p1'?' · PRO':''}</small></button>`).join('');b.querySelectorAll('.cvgoModel').forEach(x=>x.onclick=()=>select(x.dataset.id));}
  function select(id){selected=id;window.tpl=id;render(id);document.querySelectorAll('.cvgoModel').forEach(x=>x.classList.toggle('active',x.dataset.id===id));if(typeof window.cvgoServerSave==='function')window.cvgoServerSave();}
  window.cvgoSelectTemplate=select;window.template=t=>select(legacy[t]||t);
  function init(){styles();buildNav();render(selected)}setTimeout(init,300);setTimeout(init,900);setTimeout(init,1800);
})();
